### PR TITLE
LPS 149695

### PR DESCRIPTION
**Pull request by jverweijL**
- LPS-149695 Adding skeleton for new site initializer for building jobs website
- bnd update
- updated bundle name

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jverweijL** [comment]
ci:test:sf

**Comment by jverweijL** [comment]
ci:forward

**Comment by jverweijL** [comment]
ci:forward

**Comment by jverweijL** [comment]
ci:forward

**Comment by jverweijL** [comment]
ci:forward

**Comment by jverweijL** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@jverweijL, we'll try here: https://github.com/jkappler/liferay-portal/pull/1008

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
